# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rogen = "LDGerrits/rogen@1.4.4"
rojo = "rojo-rbx/rojo@7.7.0"
lune = "lune-org/lune@0.10.5"
selene = "Kampfkarren/selene@0.31.0"
